### ISSUE TITLE
Question about ETH3D

### ISSUE THREAD

**Issue by MASTERCHIEF343** [matsuren/octDPSNet#3]
I have some problems about test_ETH3D.py code.First, when I want to calculate DeepMVS result in eth3d test datasets.I found that the gt depth size is different from the DeepMVS's result beacuse of line 138 in sequence_folderse.py.So I made them both the same size 540x810.But in experiments, the error matrix calculated in our experiment is "inf".I also test DPSNet code, it has the same situation.Have you ever met this problem when you evaluate the ETH3D datasets?Especially for DeepMVS and DeMoN result.

**Comment by matsuren** [comment]
Hi @MASTERCHIEF343,
You can check my script for evaluation [here](https://github.com/matsuren/octDPSNet/blob/master/misc/ResultAnalyzeNotebook_ETH3D.ipynb).  
I think I removed invalid pixels before evaluation to avoid `inf`. If the problem is related to [the line 138 in sequence_folderse.py](https://github.com/matsuren/octDPSNet/blob/master/sequence_folderse.py#L138), just removing the invalid pixel (`pred_depth[4:, 22:]`) should be fine.
Thanks,
